baseURL = 'http://kdogadin.com'
languageCode = 'en-us'
title = 'Кирилл Догадин'
theme = 'mini'
[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
googleAnalytics = 'G-XVJP56KN1Q'
[params.google.analytics]
id = 'G-XVJP56KN1Q'
googleAnalytics = 'G-XVJP56KN1Q'
