baseURL = 'http://kdogadin.com'
languageCode = 'en-us'
title = 'Кирилл Догадин'
theme = 'mini'
[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
enableGoogleAnalytics = true
googleAnalytics = "G-XVJP56KN1Q"
